---
title: "Adonis_salinity_habitat"
author: "JRL"
date: "17/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(vegan)
library(openxlsx)
library(tidyr)
library(dplyr)
set.seed(222029)
```


```{r environnemental_data}
# Make 2 Env data tables, one for wheat, and other for noWheat. (see section below R command

env_data <- read.xlsx("sample_table_with_new_ECe_values.xlsx")
env_data <- separate(env_data, sample_id, c("wheat_presence", "site", "replicate"), sep ="_", remove = FALSE )
env_data <- mutate(env_data, wheat_presence = ifelse(wheat_presence == "B", 0, 1))
env_data <- select(env_data, sample_id, site, replicate, ECe_new_value, wheat_presence)

#Split the environnment table in two parts, one with wheat and one without wheat
env_data_wheat <- filter(env_data, wheat_presence == 1)
env_data_no_wheat <- filter(env_data, wheat_presence == 0)

#Delete the samples in env_data_no_wheat that have been deleted in the rarefied table. For fungi : B_3_1, B_9_3, B_7_3, B_5_1 and B_2_3. For bacteria : B_3_1 and B_5_2 
env_data_no_wheat_f <- filter(env_data_no_wheat, sample_id != "B_2_3", sample_id != "B_5_1", sample_id != "B_3_1", sample_id != "B_7_3", sample_id != "B_9_3")
env_data_no_wheat_b <- filter(env_data_no_wheat, sample_id != "B_3_1", sample_id != "B_5_2")
```

```{r OTU_fungi}

#Import the rarefied table for ITS2
otu_fungi <- read.xlsx("ITS2_rarefied_table.xlsx")
otu_fungi <- mutate(otu_fungi, Taxonomy = paste(otu_fungi$Kingdom, otu_fungi$Phylum, otu_fungi$Class, otu_fungi$Order, otu_fungi$Family, otu_fungi$Gender, otu_fungi$Species, sep =";")) %>% 
  select(-Kingdom, -Phylum, -Class, -Order, -Family, -Gender, -Species)
otu_fungi <- otu_fungi %>% select(Taxonomy, everything())

#Transpose the table
t_otu_fungi <- data.frame(t(otu_fungi[-1]))
colnames(t_otu_fungi) <- otu_fungi$Taxonomy

#Split the otu table in two, given the presence or absence of wheat
otu_fungi_wheat <- t_otu_fungi[-c(grep("B.", rownames(t_otu_fungi))),]
otu_fungi_no_wheat <- t_otu_fungi[-c(grep("R.", rownames(t_otu_fungi))),]
```

```{r otu_bacteria}

#Import the rarefied table for ITS2
otu_bact <- read.xlsx("16S_rarefied_table.xlsx")
otu_bact <- mutate(otu_bact, Taxonomy = paste(otu_bact$Domain, otu_bact$Phylum, otu_bact$Class, otu_bact$Order, otu_bact$Family, otu_bact$Gender, otu_bact$Species, sep =";")) %>% 
  select(-Domain, -Phylum, -Class, -Order, -Family, -Gender, -Species)
otu_bact <- otu_bact %>% select(Taxonomy, everything())

#Transpose the table
t_otu_bact <- data.frame(t(otu_bact[-1]))
colnames(t_otu_bact) <- otu_bact$Taxonomy

#Split the otu table in two, given the presence or absence of wheat
otu_bact_wheat <- t_otu_bact[-c(grep("B.", rownames(t_otu_bact))),]
otu_bact_no_wheat <- t_otu_bact[-c(grep("R.", rownames(t_otu_bact))),]
```


```{r stats}

########## FUNGI ##########

# Make bray curtis distance matrix from otu tables
bray_otu_fungi_wheat <- vegdist(otu_fungi_wheat, method="bray")
bray_otu_fungi_no_wheat  <- vegdist(otu_fungi_no_wheat, method="bray")

# Run adonis
adonis(bray_otu_fungi_wheat ~ ECe_new_value, data = env_data_wheat, strata = env_data_wheat$site, perm=999)
adonis(bray_otu_fungi_no_wheat ~ ECe_new_value, data = env_data_no_wheat_f, strata = env_data_no_wheat_f$site, perm=999)

########## BACTERIA ##########

# Make bray curtis distance matrix from otu tables
bray_otu_bact_wheat <- vegdist(otu_bact_wheat, method="bray")
bray_otu_bact_no_wheat  <- vegdist(otu_bact_no_wheat, method="bray")

# Run adonis
adonis(bray_otu_bact_wheat ~ ECe_new_value, data = env_data_wheat, strata = env_data_wheat$site, perm=999)
adonis(bray_otu_bact_no_wheat ~ ECe_new_value, data = env_data_no_wheat_b,  strata = env_data_no_wheat_b$site, perm=999)

########## BOTH ##########

# Merge the two otu tables with wheat
otu_bact_wheat2 <- tibble::rownames_to_column(otu_bact_wheat, "sample_id")
otu_fungi_wheat2 <- tibble::rownames_to_column(otu_fungi_wheat, "sample_id")
otu_both_wheat <- merge(x = otu_fungi_wheat2, y = otu_bact_wheat2, by = "sample_id" )
rownames(otu_both_wheat) <- otu_both_wheat$sample_id
otu_both_wheat <- select(otu_both_wheat, -sample_id)

# Merge the two otu tables without wheat

# Make bray curtis distance matrix from otu tables
bray_otu_both_wheat <- vegdist(otu_both_wheat, method="bray")

# Run adonis
adonis(bray_otu_bact_wheat ~ ECe_new_value, data = env_data_wheat, strata = env_data_wheat$site, perm = 999)
```

```{r heatmap_bacteria_wheat}
#The first steps aim at doing a table with the p-value of the spearman's correlation between salinity and each of the bacteria OTU

## Remove the otu where there is no read

no_zero <- colSums(otu_bact_wheat)
otu_bact_wheat <- otu_bact_wheat[-c(which(no_zero == 0, arr.ind = TRUE))]

#Other way to calculate the spearman correlation (should work better maybe for the q-values)
spearman_wheat <- Hmisc::rcorr(as.matrix(otu_bact_wheat),env_data_wheat$ECe_new_value, type = "spearman")

# The second step is to correct the p-values obtained given that the otu can be correlated.
spearman_wheat_v <- as.vector(spearman_wheat[["P"]])

# Replace the NA p-value by 1 (sure you won't select them because the p-value is too high)
spearman_wheat_v[is.na(spearman_wheat_v)] <- FALSE

# ad0_bact_wheat_v <- as.vector(ad0_bact_wheat)
adjusted_wheat <- fdrtool::fdrtool(spearman_wheat_v, "pvalue")

```


