---
title: "Material and Method"
author: "Microbiome group"
date: "26/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(tidyr)
```


```{r samples_table, echo=FALSE}
samples <- read_csv2("Samples.csv") %>% 
# The two last rows must be deleted because they explain ECe
  head(-2) %>%
  
  # rename the columns with spaces
  rename(c("site_id" = "Site number", "pH_water" = "pHwater (bulk soil)", "Altitude" = "Altitude (m)")) %>% 

# Split the sample names columns in two parts, one for the bulk, the other one for the rhizosphere
  separate("Sample name of bulk/rhizopheric soils", c("bulk", "rhizo"), sep = "/") %>%
# Split the ECe in two parts, one for bulk, the other one for rhizosphere
  separate("ECe of bulk/rhizopheric soils", c("ECe_bulk", "ECe_rhizo"), sep = "/") %>%
# group all the sample's id and ECE values together
  pivot_longer(cols = c("bulk","rhizo"), names_to = "sample_type", values_to = "sample_id") %>%
  pivot_longer(cols = c("ECe_bulk","ECe_rhizo"), names_to = "ECe_type", values_to = "ECe_value")

#change the type of ECe from character to numeric

samples$ECe_value <- gsub(',','.',samples$ECe_value)
samples$ECe_value <- as.numeric(samples$ECe_value)

# delete the doubles

(samples_def <- filter(samples, (sample_type=="bulk" & ECe_type=="ECe_bulk")|(sample_type=="rhizo" & ECe_type=="ECe_rhizo")) %>% 
  mutate(pH_water = ifelse(sample_type == "rhizo", NA, pH_water))) %>%  #we delete the pH value from the rhizo types

#change the values of the ECe : Siti and John used the coefficient 6.5 and we want tu use 6.75
  mutate(ECe_value = ECe_value*6.75/6.5) %>% 
  select(sample_id, Longitude, Latitude, pH_water, ECe_value)



#print all the rows
print(samples_def, n = 50)
 
```
```{r export_ECe_values}
library(openxlsx)
library(rio)
export(samples_def,"sample_table_with_new_ECe_values.xlsx")
```

