---
title: "Tables_summarising_ITS2"
author: "JRL"
date: "11/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(purrr)
library(openxlsx)
library(ggplot2)
library(tidyverse)
```


```{r cars}

(df <- as.data.frame(read.xlsx("ITS2_rarefied_table.xlsx")))
# Tidy the names from the imported table (no spaces, no number in taxonomic columns)
df$Phylum <- gsub(" ","", df$Phylum)
df$Order <- gsub(" ", "", df$Order)
df$Family <- gsub(" ", "", df$Family)
df$Gender <- gsub(" ", "", df$Gender)
df$Gender <- gsub("\\d","", df$Gender)
df$Gender <- gsub("([[:punct:]]\\d)","", df$Gender)
```


```{r percentages_per_read}
## PHYLUM
df_phylum <- na.omit(df[,-c(1,3:7)])
ad0 <- as.vector(NULL)
for (s in 2:ncol(df_phylum)) {
  sum_phylum <- tapply(df_phylum[,s], as.factor(df_phylum$Phylum), sum)
   ad <- tapply(df_phylum[,s], as.factor(df_phylum$Phylum), sum)*100 / sum(df_phylum[,s])
   ad0 <- cbind(ad0,ad)
}
colnames(ad0)<-names(df_phylum)[2:ncol(df_phylum)]

#Percentage of unidentified phylum
pct_p <- (sum_phylum["unidentified"]/sum(sum_phylum))*100

#Percentage in sequences of Ascomycota, Basidiomycota and Mortierellomycota
pct_asco <- (sum_phylum["Ascomycota"]/sum(sum_phylum))*100
pct_basidio <- (sum_phylum["Basidiomycota"]/sum(sum_phylum))*100
pct_mortie <- (sum_phylum["Mortierellomycota"]/sum(sum_phylum))*100
(pct_muco <- (sum_phylum["Mucoromycota"]/sum(sum_phylum))*100)

##ORDER
df_order <- na.omit(df[,-c(1:3,5:7)])
ad0_o <- as.vector(NULL)
for (s in 2:ncol(df_order)) {
  sum_order <- tapply(df_order[,s], as.factor(df_order$Order), sum)
   ad_o <- tapply(df_order[,s], as.factor(df_order$Order), sum)*100 / sum(df_order[,s])
   ad0_o <- cbind(ad0_o,ad_o)
}
colnames(ad0_o)<-names(df_order)[2:ncol(df_phylum)]

#Pct unidentified order
pct_o <- (sum_order["unidentified"]/sum(sum_order))*100

##FAMILY
df_family <- na.omit(df[,-c(1:4,6:7)])
ad0_f <- as.vector(NULL)
for (s in 2:ncol(df_family)) {
   ad_f <- tapply(df_family[,s], as.factor(df_family$Family), sum)*100 / sum(df_family[,s])
   ad0_f <- cbind(ad0_f,ad_f)
}
colnames(ad0_f)<-names(df_family)[2:ncol(df_family)]


##GENDER
df_gender <- na.omit(df[,-c(1:5,7)])
ad0_g <- as.vector(NULL)
for (s in 2:ncol(df_gender)) {
  sum_gender <- tapply(df_gender[,s], as.factor(df_gender$Gender), sum)
  ad_g <- tapply(df_gender[,s], as.factor(df_gender$Gender), sum)*100 / sum(df_gender[,s])
  ad0_g <- cbind(ad0_g,ad_g)
}
colnames(ad0_g)<-names(df_gender)[2:ncol(df_gender)]

#Pct unidentified order
pct_g <- (sum_gender["unidentified"]/sum(sum_gender))*100

nrow(ad0)
nrow(ad_o)
nrow(ad_f)
nrow(ad_g)
nrow(df)
```

```{r percentage_per_otu}

#Phylum
df_phylum_sorted <- filter(df_phylum, Phylum == "unidentified")
(pct <- (nrow(df_phylum_sorted)/nrow(df))*100)

#Gender
df_gender_sorted <- filter(df_gender, Gender == "unidentified")
(pct <- (nrow(df_gender_sorted)/nrow(df))*100) 

```


