---
title: "ITS2_biodiversity_indexes"
author: "JRL"
date: "15/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import tables}
df_phylum <- read.xlsx("ITS2_phylum_reads.xlsx")
df_order <- read.xlsx("ITS2_order_reads.xlsx")
df_family <- read.xlsx("ITS2_family_reads.xlsx")
df_gender <- read.xlsx("ITS2_gender_reads.xlsx")
```


```{r phylum}

# Phylum of ITS2 

#Transpose the table

t_df_phylum <- data.frame(t(df_phylum[-1]))

# Shannon for Phylum of ITS2

t_df_phylum <- data.frame(t(df_phylum[-1]))
shann_phylum_ITS2 <- diversity(t_df_phylum, index = "shannon", MARGIN = 1, base = exp(1))
write.csv(shann_phylum_ITS2, file = "shann_phylum_ITS2.csv", row.names = TRUE)

# Simpson for Phylum of ITS2

simp_phylum_ITS2 <- diversity(t_df_phylum, index = "simpson", MARGIN = 1, base = exp(1))
write.csv(simp_phylum_ITS2, file = "simp_phylum_ITS2.csv", row.names = TRUE)

# Chao1 for Phylum of ITS2

chao_phylum_ITS2 <- estimateR(t_df_phylum)
write.csv(chao_phylum_ITS2, file = "chao.csv", row.names = TRUE)
```

```{r order}

# Order of ITS2

#Transpose the table

t_df_order<- data.frame(t(df_order[-1]))

# Shannon for Order of ITS2

shann_order_ITS2 <- diversity(t_df_order, index = "shannon", MARGIN = 1, base = exp(1))
write.csv(shann_order_ITS2, file = "shann_order_ITS2.csv", row.names = TRUE)

# Simpson for Order of ITS2

simp_order_ITS2 <- diversity(t_df_order, index = "simpson", MARGIN = 1, base = exp(1))
write.csv(simp_order_ITS2, file = "simp_order_ITS2.csv", row.names = TRUE)

# Chao1 for Order of ITS2

chao_order_ITS2 <- estimateR(t_df_order)
write.csv(chao_order_ITS2, file = "chao_order_ITS2.csv", row.names = TRUE)
```

```{r family}
# Family of ITS2

#Transpose the table

t_df_family <- data.frame(t(df_family[-1]))

# Shannon for Family of ITS2

shann_family_ITS2 <- diversity(t_df_family, index = "shannon", MARGIN = 1, base = exp(1))
write.csv(shann_family_ITS2, file = "shann_family_ITS2.csv", row.names = TRUE)

# Simpson for Family of ITS2

simp_family_ITS2 <- diversity(t_df_family, index = "simpson", MARGIN = 1, base = exp(1))
write.csv(simp_family_ITS2, file = "simp_family_ITS2.csv", row.names = TRUE)

# Chao1 for Family of ITS2

chao_family_ITS2 <- estimateR(t_df_family)
write.csv(chao_family_ITS2, file = "chao_family_ITS2.csv", row.names = TRUE)
```

```{r gender}
# Gender of ITS2

#Transpose the table

t_df_gender <- data.frame(t(df_gender[-1]))

# Shannon for Gender of ITS2

shann_gender_ITS2 <- diversity(t_df_gender, index = "shannon", MARGIN = 1, base = exp(1))
write.csv(shann_gender_ITS2, file = "shann_gender_ITS2.csv", row.names = TRUE)

# Simpson for Gender of ITS2

simp_gender_ITS2 <- diversity(t_df_gender, index = "simpson", MARGIN = 1, base = exp(1))
write.csv(simp_gender_ITS2, file = "simp_gender_ITS2.csv", row.names = TRUE)

# Chao1 for Gender of ITS2

chao_gender_ITS2 <- estimateR(t_df_gender)
write.csv(chao_gender_ITS2, file = "chao_gender_ITS2.csv", row.names = TRUE)
```

