---
title: "ITS2_grouping_phylum_gender"
author: "JRL"
date: "10/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(purrr)
library(openxlsx)
library(ggplot2)
library(tidyverse)
```


```{r phylum_with_unidentified}

(df <- as.data.frame(read.xlsx("ITS2_rarefied_table.xlsx")))
# Tidy the names from the imported table (no spaces, no number in Phylum and Gender columns)
df$Phylum <- gsub(" ","", df$Phylum)
df$Gender <- gsub(" ","", df$Gender)
df$Gender <- gsub("\\d","", df$Gender)
df$Gender <- gsub("([[:punct:]]\\d)","", df$Gender)

## DATA SET TO USE

df_phylum <- na.omit(df[,-c(1,3:7)])
ad0 <- as.vector(NULL)
for (s in 2:ncol(df_phylum)) {
   ad <- tapply(df_phylum[,s], as.factor(df_phylum$Phylum), sum)*100 / sum(df_phylum[,s])
   ad0 <- cbind(ad0,ad)
}
colnames(ad0)<-names(df_phylum)[2:ncol(df_phylum)]

## Verification
colSums(ad0)

#Selecting the samples colums only
ad0_w_unident <- as_tibble(ad0, rownames = NA)
ad0_w_unident <- select(ad0_w_unident,starts_with("B"), starts_with("R"))
```

```{r phylum_without_unidentified}

#We remove the lines with an unidentified phylum
df_phylum_no_unident <- filter(df_phylum, Phylum != "unidentified")

#We calculate the percentages without the unidentifed phylums
ad0_no_unident <- as.vector(NULL)
for (s in 2:ncol(df_phylum_no_unident)) {
   ad_no_unident <- tapply(df_phylum_no_unident[,s], as.factor(df_phylum_no_unident$Phylum), sum)*100 / sum(df_phylum_no_unident[,s])
   ad0_no_unident <- cbind(ad0_no_unident,ad_no_unident)
}
colnames(ad0_no_unident)<-names(df_phylum_no_unident)[2:ncol(df_phylum_no_unident)]

## Verification
colSums(ad0_no_unident)

#Selecting the samples colums only
ad0_no_unident <- as_tibble(ad0_no_unident, rownames = NA)
ad0_no_unident <- select(ad0_no_unident,starts_with("B"), starts_with("R"))

```


```{r percentage_barchart_phylum_with_unidentified}

# Create a phylum column so that we can plot it
ad0_w_unident <- mutate(ad0_w_unident, Phylum = rownames(ad0_w_unident)) %>% 
  select(Phylum, everything())

#Tidy your dataset 
ad0_w_unident <- pivot_longer(ad0_w_unident, cols= B_2_1:R_9_3, names_to = "Samples", values_to = "Pct_phylum")
 
# Stacked + percent
ggplot(data = ad0_w_unident, mapping = aes(x = Samples, y = Pct_phylum, fill=Phylum )) + 
   geom_bar(position="fill", stat="identity") +
   geom_vline(aes(intercept = Samples, xintercept = "R_2_1")) +
   theme(axis.text.x = element_text(angle=90))
```
```{r percentage_barchart_phylum_no_unidentified}

# Create a phylum column so that we can plot it
ad0_no_unident <- mutate(ad0_no_unident, Phylum = rownames(ad0_no_unident)) %>% 
  select(Phylum, everything())

#Tidy your dataset 
ad0_no_unident <- pivot_longer(ad0_no_unident, cols= B_2_1:R_9_3, names_to = "Samples", values_to = "Pct_phylum")
 
# Stacked + percent
ggplot(data = ad0_no_unident, mapping = aes(x = Samples, y = Pct_phylum, fill=Phylum )) + 
   geom_bar(position="fill", stat="identity") +
   geom_vline(aes(intercept = Samples, xintercept = "R_2_1")) +
   theme(axis.text.x = element_text(angle=90))

```


```{r gender_w_unident }

df_gender <- na.omit(df[,-c(1:5,7)])
ad1 <-as.vector(NULL)
for (s in 2:ncol(df_gender)) {
   ad <- tapply(df_gender[,s], as.factor(df_gender$Gender), sum)*100 / sum(df_gender[,s])
   ad1 <-cbind(ad1,ad)
}
colnames(ad1)<-names(df_gender)[2:ncol(df_gender)]

## Verification
colSums(ad1)

#Selecting the samples colums only
ad1_w_unident <- as_tibble(ad1, rownames = NA)
ad1_w_unident <- select(ad1_w_unident,starts_with("B"), starts_with("R"))

```

```{r table_gender_no_unident}

#We remove the lines with an unidentified phylum
df_gender_no_unident <- filter(df_gender, Gender != "unidentified")

#We calculate the percentages without the unidentifed phylums
ad1_no_unident <- as.vector(NULL)
for (s in 2:ncol(df_gender_no_unident)) {
   ad_no_unident <- tapply(df_gender_no_unident[,s], as.factor(df_gender_no_unident$Gender), sum)*100 / sum(df_gender_no_unident[,s])
   ad1_no_unident <- cbind(ad1_no_unident,ad_no_unident)
}
colnames(ad1_no_unident)<-names(df_gender_no_unident)[2:ncol(df_gender_no_unident)]

## Verification
colSums(ad1_no_unident)

#Selecting the samples colums only
ad1_no_unident <- as_tibble(ad1_no_unident, rownames = NA)
ad1_no_unident <- select(ad1_no_unident,starts_with("B"), starts_with("R"))
```

```{r percentage_barchart_gender_with_unidentified}

# Create a phylum column so that we can plot it
ad1_w_unident <- mutate(ad1_w_unident, Gender = rownames(ad1_w_unident)) %>% 
  select(Gender, everything())

#Tidy your dataset 
ad1_w_unident <- pivot_longer(ad1_w_unident, cols= B_2_1:R_9_3, names_to = "Samples", values_to = "Pct_gender")
 
# Stacked + percent
(ggplot(data = ad1_w_unident, mapping = aes(x = Samples, y = Pct_gender, fill=Gender )) + 
   geom_bar(position="fill", stat="identity") +
   geom_vline(aes(intercept = Samples, xintercept = "R_2_1")) +
   theme(axis.text.x = element_text(angle=90))
)
```

```{r pct_barchart_gender_no_unidentified, echo=FALSE}
# Create a phylum column so that we can plot it
ad1_no_unident <- mutate(ad1_no_unident, Gender = rownames(ad1_no_unident)) %>% 
  select(Gender, everything())

#Tidy your dataset 
ad1_no_unident <- pivot_longer(ad1_no_unident, cols= B_2_1:R_9_3, names_to = "Samples", values_to = "Pct_gender")
 
# Stacked + percent
ggplot(data = ad1_no_unident, mapping = aes(x = Samples, y = Pct_gender, fill=Gender)) + 
   geom_bar(position="fill", stat="identity", show.legend = FALSE) +
   geom_vline(aes(intercept = Samples, xintercept = "R_2_1")) +
   theme(axis.text.x = element_text(angle=90))
```

