---
title: "Tables_group_by_taxa"
author: "JRL"
date: "11/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(purrr)
library(openxlsx)
library(tidyverse)
library(vegan)
```


```{r tidy_data}

(df <- as.data.frame(read.xlsx("ITS2_rarefied_table.xlsx")))

# Tidy the names from the imported table (no spaces, no number in Phylum and Gender columns)
df$Phylum <- gsub(" ","", df$Phylum)
df$Gender <- gsub(" ","", df$Gender)
df$Gender <- gsub("\\d","", df$Gender)
df$Gender <- gsub("([[:punct:]]\\d)","", df$Gender)
```


```{r phylum}

#Select the phylum column
df_phylum <- na.omit(df[,-c(1,3:7)])

#Calculate the number of reads per sample for each phylum
df_phylum_sorted <- pivot_longer(df_phylum, cols= B_2_1:R_9_3, names_to = "Samples", values_to = "Nb_reads") 
df_phylum_sorted <- group_by(df_phylum_sorted, Samples, Phylum) %>% 
  summarise(Nb_reads = sum(Nb_reads))

#Wide the table so that one sample has one line
df_phylum_sorted <- pivot_wider(df_phylum_sorted, names_from = Phylum, values_from = Nb_reads)

#export the dataset
write.xlsx(df_phylum_sorted,"ITS2_phylum_reads.xlsx")
```


```{r order}
df_order <- na.omit(df[,-c(1:3,5:7)])

#Calculate the number of reads per sample for each order
df_order_sorted <- pivot_longer(df_order, cols= B_2_1:R_9_3, names_to = "Samples", values_to = "Nb_reads") 
df_order_sorted <- group_by(df_order_sorted, Samples, Order) %>% 
  summarise(Nb_reads = sum(Nb_reads))

#Wide the table so that one sample has one line
(df_order_sorted <- pivot_wider(df_order_sorted, names_from = Order, values_from = Nb_reads))

#export the dataset
write.xlsx(df_order_sorted,"ITS2_order_reads.xlsx")

```

```{r family}
df_family <- na.omit(df[,-c(1:4,6:7)])

#Calculate the number of reads per sample for each order
df_family_sorted <- pivot_longer(df_family, cols= B_2_1:R_9_3, names_to = "Samples", values_to = "Nb_reads") 
df_family_sorted <- group_by(df_family_sorted, Samples, Family) %>% 
  summarise(Nb_reads = sum(Nb_reads))

#Wide the table so that one sample has one line
(df_family_sorted <- pivot_wider(df_family_sorted, names_from = Family, values_from = Nb_reads))

#export the dataset
write.xlsx(df_family_sorted,"ITS2_family_reads.xlsx")

```

```{r gender}
df_gender <- na.omit(df[,-c(1:5,7)])

#Calculate the number of reads per sample for each order
df_gender_sorted <- pivot_longer(df_gender, cols= B_2_1:R_9_3, names_to = "Samples", values_to = "Nb_reads") 
df_gender_sorted <- group_by(df_gender_sorted, Samples, Gender) %>% 
  summarise(Nb_reads = sum(Nb_reads))

#Wide the table so that one sample has one line
(df_gender_sorted <- pivot_wider(df_gender_sorted, names_from = Gender, values_from = Nb_reads))

#export the dataset
write.xlsx(df_gender_sorted,"ITS2_gender_reads.xlsx")
```
```{r}
## BIODIVERSITY INDICATORS


# Phylum of ITS2 

#Transpose the table

t_df_phylum_sorted <- data.frame(t(df_phylum_sorted[-1]))

# Shannon for Phylum of ITS2

t_df_phylum_sorted <- data.frame(t(df_phylum_sorted[-1]))
shann_phylum_ITS2 <- diversity(t_df_phylum_sorted, index = "shannon", MARGIN = 1, base = exp(1))
write.csv(shann_phylum_ITS2, file = "shann_phylum_ITS2.csv", row.names = TRUE)

# Simpson for Phylum of ITS2

simp_phylum_ITS2 <- diversity(t_df_phylum_sorted, index = "simpson", MARGIN = 1, base = exp(1))
write.csv(simp_phylum_ITS2, file = "simp_phylum_ITS2.csv", row.names = TRUE)

# Chao1 for Phylum of ITS2

chao_phylum_ITS2 <- estimateR(t_df_phylum_sorted)
write.csv(chao_phylum_ITS2, file = "chao.csv", row.names = TRUE)


# Order of ITS2

#Transpose the table

t_df_order_sorted <- data.frame(t(df_order_sorted[-1]))

# Shannon for Order of ITS2

shann_order_ITS2 <- diversity(t_df_order_sorted, index = "shannon", MARGIN = 1, base = exp(1))
write.csv(shann_order_ITS2, file = "shann_order_ITS2.csv", row.names = TRUE)

# Simpson for Order of ITS2

simp_order_ITS2 <- diversity(t_df_order_sorted, index = "simpson", MARGIN = 1, base = exp(1))
write.csv(simp_order_ITS2, file = "simp_order_ITS2.csv", row.names = TRUE)

# Chao1 for Order of ITS2

chao_order_ITS2 <- estimateR(t_df_order_sorted)
write.csv(chao_order_ITS2, file = "chao_order_ITS2.csv", row.names = TRUE)


# Family of ITS2

#Transpose the table

t_df_family_sorted <- data.frame(t(df_family_sorted[-1]))

# Shannon for Family of ITS2

shann_family_ITS2 <- diversity(t_df_family_sorted, index = "shannon", MARGIN = 1, base = exp(1))
write.csv(shann_family_ITS2, file = "shann_family_ITS2.csv", row.names = TRUE)

# Simpson for Family of ITS2

simp_family_ITS2 <- diversity(t_df_family_sorted, index = "simpson", MARGIN = 1, base = exp(1))
write.csv(simp_family_ITS2, file = "simp_family_ITS2.csv", row.names = TRUE)

# Chao1 for Family of ITS2

chao_family_ITS2 <- estimateR(t_df_family_sorted)
write.csv(chao_family_ITS2, file = "chao_family_ITS2.csv", row.names = TRUE)


# Gender of ITS2

#Transpose the table

t_df_gender_sorted <- data.frame(t(df_gender_sorted[-1]))

# Shannon for Gender of ITS2

shann_gender_ITS2 <- diversity(t_df_gender_sorted, index = "shannon", MARGIN = 1, base = exp(1))
write.csv(shann_gender_ITS2, file = "shann_gender_ITS2.csv", row.names = TRUE)

# Simpson for Gender of ITS2

simp_gender_ITS2 <- diversity(t_df_gender_sorted, index = "simpson", MARGIN = 1, base = exp(1))
write.csv(simp_gender_ITS2, file = "simp_gender_ITS2.csv", row.names = TRUE)

# Chao1 for Gender of ITS2

chao_gender_ITS2 <- estimateR(t_df_gender_sorted)
write.csv(chao_gender_ITS2, file = "chao_gender_ITS2.csv", row.names = TRUE)


```

