---
title: "Pct of OTU per sample"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(openxlsx)
library(readxl)
library(expss)
library(purrr)
library(rio)
library(tidyverse)
library(purrr) 
library(tidyr)
```


```{r import_excel_files, echo=FALSE}
(assignment_table <-as.data.frame(read.xlsx("16s_rarefied_table.xlsx")))

```
```{r}
#Change NA -> Unidentified
x0<-as.vector(NULL)
for (i in 1:7) {  x1 <- replace_na(assignment_table[,i],"Unidentified")  
x0 <- cbind(x0,x1) 
}
new_assign_table <- cbind(x0,assignment_table[,8:length(assignment_table)])
names(new_assign_table) <- names(assignment_table) 

```

```{r data}
## DATA SET TO USE PHYLUM
assign_table_2 <- new_assign_table[,-c(1,3:7)]
ad0 <- as.vector(NULL)
(for (s in 2:ncol(assign_table_2))
  {
   ad <- tapply(assign_table_2[,s], as.factor(assign_table_2$Phylum), sum)*100 / sum(assign_table_2[,s])
   ad0 <- cbind(ad0,ad)
})
colnames(ad0)<-names(assign_table_2)[2:ncol(assign_table_2)]
assign_table_2
otu_pct <- data.frame(ad0)
Phylum <- rownames(ad0)
otu_pct_2 <- cbind(Phylum,otu_pct)
otu_pct_2


```
``` {r excel}

export(otu_pct_2, "16s_pct.Otu.phylum.xlsx")
getwd()

```
```{r data}
## Verification
colSums(ad0)
```
```{r gender}
## DATA SET TO USE GENDER
assign_table_3 <- new_assign_table[,-c(1:5,7)]
ad0g <- as.vector(NULL)
(for (s in 2:ncol(assign_table_3))
  {
   adg <- tapply(assign_table_3[,s], as.factor(assign_table_3$Gender), sum)*100 / sum(assign_table_3[,s])
   ad0g <- cbind(ad0g,adg)
})
colnames(ad0g)<-names(assign_table_3)[2:ncol(assign_table_3)]
ad0g
otu_pct_3 <- data.frame(ad0g)
Gender <- rownames(ad0g)
otu_pct_gender <- cbind(Gender,otu_pct_3)
otu_pct_gender
```


```{r data}
## Verification
colSums(ad0g)
```

```{r}
#export excel
export(otu_pct_gender, "16s_pct.Otu.gender.xlsx")
getwd()

```