---
title: "Untitled"
author: "JRL"
date: "03/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
```


```{r taxa_assignment_table, echo=FALSE}
library(readxl)
(taxa_assignment_table <- read_excel("taxa_assignment_table.xlsx"))
View(taxa_assignment_table)

```
```{r list_contaminated_OTU, echo=FALSE}
(tot_read_PCR <- select(taxa_assignment_table, PCRCont) %>% 
  colSums())
(taxa_assignment_table %>% filter(PCRCont !=0) %>% 
  mutate(pct_cont_OTU_PCR = (PCRCont/tot_read_PCR)*100))
```

Only two OTU contaminated the samples at the PCR step (We have no contaminants in External contaminant sample)

```{r list_contaminated_OTU, echo=FALSE}
(tot_read_ExtCont <- select(taxa_assignment_table, ExtCont) %>% 
  colSums())
(taxa_assignment_table %>% filter(ExtCont !=0) %>% 
  mutate(ext_cont_OTU_PCR = (ExtCont/tot_read_PCR)*100))
```
```{r list_contaminated_OTU, echo=FALSE}
(tot_read_MockCom <- select(taxa_assignment_table, MockCom) %>% 
  colSums())
(taxa_assignment_table %>% filter(MockCom !=0) %>% 
  mutate(mock_com_OTU_PCR = (MockCom/tot_read_PCR)*100))
```