---
title: "Assignment_rarefaction"
author: "JRL"
date: "05/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(vegan)
library(tidyr)
library(openxlsx)
library(rio)
```


```{r import_tables, warning=TRUE, include=FALSE}
# Importing the tables to merge and skip the first line for feature

taxonomy_table <- read_tsv("ITS2_taxonomy_jrl2020.tsv")
View(taxonomy_table)
feature_table <- read_tsv("ITS2_feature-table.tsv", skip = 1)
View(feature_table)
```



```{r assignment_table, echo=FALSE}

# Merging the tables

assignment_table <- merge(taxonomy_table, feature_table, by.x = "Feature ID", "#OTU ID")
View(assignment_table)

# Changing names

assignment_table <- rename(assignment_table, "Feature_ID"="Feature ID")
assignment_table <- rename(assignment_table, "B_2_3"="B-2-3")

# Selecting only the taxon and samples columns + Removing B-2-3, EstCont and MockCom

(assignment_table <- select(assignment_table, -Feature_ID, -Confidence, -B_2_3, -ExtCont, -MockCom))

taxa_assignment_table <- separate(data = assignment_table, col = Taxon, sep = "([pcofgs]__)", into = c("Kingdom","Phylum","Class","Order","Family","Gender","Species"))
taxa_assignment_table$Phylum <-  gsub(";","",taxa_assignment_table$Phylum)
taxa_assignment_table$Class <-  gsub(";","",taxa_assignment_table$Class)
taxa_assignment_table$Order <-  gsub(";","",taxa_assignment_table$Order)
taxa_assignment_table$Family <-  gsub(";","",taxa_assignment_table$Family)
taxa_assignment_table$Gender <-  gsub(";","",taxa_assignment_table$Gender)
taxa_assignment_table$Kingdom <-  gsub(";","",taxa_assignment_table$Kingdom)
taxa_assignment_table$Kingdom <-  gsub("k__","",taxa_assignment_table$Kingdom)
View(taxa_assignment_table)

```

```{r}
# Total number of reads for unidentified taxa

(unidentified_taxa <- taxa_assignment_table %>% 
  filter(Phylum == "unidentified"))

unidentified_taxa <- select( unidentified_taxa, -c(1:7))

sum(rowSums(unidentified_taxa))
  

#

all_taxa <- select( taxa_assignment_table, -c(1:7))

sum(rowSums(all_taxa))
  
```


```{r rarefaction}
# To do the rarefaction curve it's needed to switch the columns and lines from the table
no_taxa <- assignment_table[-1]
(t_assignment_table <- data.frame(t(no_taxa)))
colnames(t_assignment_table) <- assignment_table[,1]
rownames(t_assignment_table) <- colnames(no_taxa[1,])
View(t_assignment_table)

# We also need to delete PCRCont and ExtCont from the dataframe

assignment_table_rare1 <-  t_assignment_table[
                                            grep("[\\-]", rownames(t_assignment_table)),]

# Rarefaction curve

  OTU <- specnumber(assignment_table_rare1) # It counts the number of OTU
  raremax <- min(rowSums(assignment_table_rare1)) #Look at the minimum number of reads in the   samples
  print(rowSums(assignment_table_rare1))

  Srare <- rarefy(assignment_table_rare1, raremax) #Function rarefy gives the expected species richness in random subsamples of size 'raremax' from the community
  
  # Plot the rarefaction curve
plot(OTU, Srare, xlab = "Observed No. of Species", ylab = "Rarefied No. of Species")
rarecurve(assignment_table_rare1, step = 20, sample = raremax, col = "blue", cex = 0.6, ylab = "OTU number")

```

As we can see on the graph and int the printed rowSums, B-9-3, B-7-3, B-5-1 and B-3-1 should be deleted, so that we can have a correct rarefied table

```{r rarefied_df}

#Delete  B-9-3, B-7-3 and B-3-1
assignment_table_rare2 <- assignment_table_rare1[
                                          -c(grep("B-9-3", rownames(t_assignment_table), fixed = TRUE), 
                                             grep("B-7-3", rownames(t_assignment_table), fixed = TRUE), 
                                             grep("B-3-1", rownames(t_assignment_table), fixed = TRUE),
                                             grep("B-5-1", rownames(t_assignment_table), fixed = TRUE)),]

# Rarefaction curve

  OTU <- specnumber(assignment_table_rare2) # It counts the number of OTU
  raremax <- min(rowSums(assignment_table_rare2)) #Look at the minimum number of reads in the   samples


  Srare <- rarefy(assignment_table_rare2, raremax) #Function rarefy gives the expected species richness in random subsamples of size 'raremax' from the community
  
  # Plot the rarefaction curve
plot(OTU, Srare, xlab = "Observed No. of Species", ylab = "Rarefied No. of Species")
rarecurve(assignment_table_rare2, step = 20, sample = raremax, col = "blue", cex = 0.6, ylab = "OTU number")

  #Rarefy the dataframe
set.seed(seed = 222029)
rarefied_df <- rrarefy(assignment_table_rare2, raremax)


```
The rarefied number reaches 17129 after removing these 4 samples  
